---
- name: Ensure Evebox Directory Exist
  file:
    path: "{{project_directory}}/evebox"
    state: directory
  tags: evebox

- name: Create Evebox Docker Container
  docker_container:
    name: evebox
    image: "jasonish/evebox:{{evebox_version}}"
    pull: yes
    hostname: evebox
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: absent
    volumes:
      - "{{project_directory}}/evebox:/data"
    labels:
      traefik.http.routers.evebox.entrypoints: "websecure"
      traefik.http.routers.evebox.tls: "true"
      traefik.http.routers.evebox.rule: "Host(`evebox.{{project_tld}}`)"
      traefik.http.routers.evebox.service: "evebox"
      traefik.http.services.evebox.loadbalancer.server.port: "5636"
      traefik.enable: "true"
  tags: evebox
