---
- name: Ensure MondoDB Databases are Present.
  mongodb_user:
    login_host: "{{mongo_host}}"
    login_port: "{{mongo_port}}"
    login_user: "{{mongo_initdb_root_username}}"
    login_password: "{{mongo_initdb_root_password}}"
    database: "{{database_name}}"
    name: "{{database_user}}"
    password: "{{database_password}}"
    roles: readWrite,dbAdmin,userAdmin
    state: present
    update_password: on_create