---
- name: Create Node Exporter Docker Container
  docker_container:
    name: node-exporter
    image: "prom/node-exporter:{{grafana_stack_version}}"
    pull: yes
    hostname: nodeexporter
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    command:
      --path.procfs=/host/proc
      --path.sysfs=/host/sys
      --collector.filesystem.ignored-mount-points
      "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
  tags:
    - node-exporter
    - prometheus
    - grafana