---
kind: pipeline
name: workbench

steps:
- name: start-notify
  image: plugins/matrix
  settings:
    homeserver: https://authoritah.chat
    roomid: "!TMwevAOtFwsPYDoFNR:authoritah.chat"
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    template: "Build Started [{{ repo.Owner }}/{{ repo.Name }}#{{ truncate build.commit 8 }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}"

- name: check ansible syntax
  image: plugins/ansible:1
  settings:
    playbook: site.yml
    inventory: production
    syntax_check: true

- name: apply ansible playbook
  image: plugins/ansible:1
  settings:
    playbook: site.yml
    inventory: production
    private_key:
      from_secret: ansible_private_key
    vault_password:
      from_secret: ansible_vault_password

- name: succeess-notify
  image: plugins/matrix
  settings:
    homeserver: https://authoritah.chat
    roomid: "!TMwevAOtFwsPYDoFNR:authoritah.chat"
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    template: "Build {{ build.status }} [{{ repo.Owner }}/{{ repo.Name }}#{{ truncate build.commit 8 }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}"
  when:
    status:
    - success

- name: failure-notify
  image: plugins/matrix
  settings:
    homeserver: https://authoritah.chat
    roomid: "!TMwevAOtFwsPYDoFNR:authoritah.chat"
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    template: "Build Failed [{{ repo.Owner }}/{{ repo.Name }}#{{ truncate build.commit 8 }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}"
  when:
    status:
    - failure
