repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: trailing-whitespace
            name: Trim Trailing Whitespace
            description: This hook trims trailing whitespace.
            entry: trailing-whitespace-fixer