---
    - name: Restart LANcache DNS
      docker_container:
        name: lancache-dns
        restart: yes
      listen: restart lancache-dns

    - name: Restart SNI Proxy
      docker_container:
        name: sniproxy
        restart: yes
      listen: restart sniproxy

    - name: Restart Monolithic
      docker_container:
        name: monolithic
        restart: yes
      listen: restart monolithic