---
- name: Ensure Element Directory Exist
  file:
    path: "{{project_directory}}/element"
    state: directory
    owner: "8675309"
    group: "8675309"
  tags: matrix

- name: Ensure Element Configuration Files Exist
  template:
    src: element-config.json.j2
    dest: "{{project_directory}}/element/config.json"
    owner: "8675309"
    group: "8675309"
  no_log: true
  tags: matrix

- name: Create Element Docker Container
  docker_container:
    name: element
    image: "bubuntux/riot-web:{{element_version}}"
    pull: yes
    hostname: element
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    env:
      PUID: "8675309"
      PGID: "8675309"
      TZ: "{{default_timezone}}"
    volumes:
      - "{{project_directory}}/element/config.json:/etc/riot-web/config.json:ro"
    labels:
      traefik.http.routers.element.entrypoints: "websecure"
      traefik.http.routers.element.tls: "true"
      traefik.http.routers.element.rule: "Host(`element.{{chat_tld}}`)"
      traefik.http.routers.element.middlewares: "default-headers@file"
      traefik.http.routers.element.service: "element"
      traefik.http.services.element.loadbalancer.server.port: "80"
      traefik.enable: "true"
  tags: matrix
