---
- name: Ensure FreshRSS Directory Exist
  file:
    path: "{{project_directory}}/freshrss"
    state: directory
  tags: freshrss

- import_tasks: roles/postgres/tasks/database_manager.yml
  vars:
    database_name: "{{freshrss_database}}"
    database_user: "{{freshrss_database_user}}"
    database_password: "{{freshrss_database_password}}"
  tags: freshrss
  no_log: true

- name: Create FreshRSS Docker Container
  docker_container:
    name: freshrss
    image: "linuxserver/freshrss:{{freshrss_version}}"
    pull: yes
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    comparisons:
      '*': strict
    state: started
    env:
      POSTGRES_DB: "{{freshrss_database}}"
      POSTGRES_USER: "{{freshrss_database_user}}"
      POSTGRES_PASSWORD: "{{freshrss_database_password}}"
    volumes:
      - "{{project_directory}}/freshrss:/config"
    labels:
      traefik.http.routers.freshrss.entrypoints: "websecure"
      traefik.http.routers.freshrss.tls: "true"
      traefik.http.routers.freshrss.rule: "Host(`rss.{{project_tld}}`)"
      traefik.http.routers.freshrss.service: "freshrss"
      traefik.http.services.freshrss.loadbalancer.server.port: "80"
      traefik.enable: "true"
  tags: freshrss

- name: Ensure RSS-Bridge Directory Exist
  file:
    path: "{{project_directory}}/rssbridge"
    state: directory
  tags: freshrss

- name: Ensure RSS-Bridge Configuration File Exist
  template:
    src: whitelist.txt.j2
    dest: "{{project_directory}}/rssbridge/whitelist.txt"
  tags: freshrss
  no_log: true
  notify: restart rssbridge

- name: Create RSS-Bridge Docker Container
  docker_container:
    name: rssbridge
    image: "rssbridge/rss-bridge:{{rssbridge_version}}"
    pull: yes
    hostname: freshrss
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    comparisons:
      '*': strict
    state: started
    volumes:
      - "{{project_directory}}/rssbridge/whitelist.txt:/app/whitelist.txt"
    labels:
      traefik.http.routers.rssbridge.entrypoints: "websecure"
      traefik.http.routers.rssbridge.tls: "true"
      traefik.http.routers.rssbridge.rule: "Host(`rssbridge.{{project_tld}}`)"
      traefik.http.routers.rssbridge.service: "rssbridge"
      traefik.http.services.rssbridge.loadbalancer.server.port: "80"
      traefik.enable: "true"
  tags: freshrss
