---
- name: Ensure Firefly Importer Directory Exist
  file:
    path: "{{project_directory}}/firefly/firefly-importer"
    state: directory
  tags: firefly

- name: Ensure Firefly Importer Configuration Files Exist
  template:
    src: import_env.j2
    dest: "{{project_directory}}/firefly/firefly-importer//.env"
  tags: firefly
  no_log: true
  notify: restart firefly-importer

- name: Create Firefly Importer Docker Container
  docker_container:
    name: firefly-importer
    image: "fireflyiii/csv-importer:{{firefly_version}}"
    env_file: "{{project_directory}}/firefly/firefly-importer/.env"
    pull: yes
    hostname: firefly-importer
    restart_policy: unless-stopped
    published_ports:
      - 8081:80
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    volumes:
      - "{{project_directory}}/firefly/import:/import"
  tags: firefly