---
- name: Create Drone Directory
  file:
    path: "{{project_directory}}/drone"
    state: directory
  tags: drone

- name: Create Drone Docker Container
  docker_container:
    name: drone
    image: "drone/drone:{{drone_version}}"
    user: root
    privileged: yes
    pull: yes
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    env:
      DRONE_COOKIE_SECRET: "{{drone_cookie_secret}}"
      DRONE_COOKIE_TIMEOUT: "{{drone_cookie_timeout}}"
      DRONE_GITEA_SERVER: "https://{{git_tld}}"
      DRONE_GITEA_CLIENT_ID: "{{drone_gitea_client_id}}"
      DRONE_GITEA_CLIENT_SECRET: "{{drone_gitea_client_secret}}"
      DRONE_SERVER_HOST: "ci.{{git_tld}}"
      DRONE_SERVER_PROTO: "{{drone_server_proto}}"
      DRONE_USER_CREATE: "username:nx211,admin:true"
      DRONE_SERVER_PORT: ":80"
      DRONE_AGENTS_DISABLED: "true"
    state: started
    volumes:
      - "{{project_directory}}/drone:/data"
      - /home/ansible/workbench:/home/ansible/workbench
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.routers.drone.entrypoints: "websecure"
      traefik.http.routers.drone.tls: "true"
      traefik.http.routers.drone.rule: "Host(`ci.{{git_tld}}`)"
      traefik.http.middlewares.drone-refer-header.headers.referrerPolicy: "strict-origin-when-cross-origin"
      traefik.http.routers.drone.middlewares: "drone-refer-header"
      traefik.http.routers.drone.service: "drone"
      traefik.http.services.drone.loadbalancer.server.port: "80"
      traefik.enable: "true"
  tags: drone
