---
- name: Ensure Trilium Directory Exist
  file:
    path: "{{project_directory}}/trilium"
    state: directory
  tags: trilium

- name: Create Trilium Docker Container
  docker_container:
    name: trilium
    image: "zadam/trilium:{{trilium_version}}"
    pull: yes
    hostname: trilium
    restart_policy: unless-stopped
    networks:
      - name: proxy
    networks_cli_compatible: yes
    state: started
    volumes:
      - "{{project_directory}}/trilium:/root/trilium-data"
    labels:
      traefik.http.routers.trilium.entrypoints: "websecure"
      traefik.http.routers.trilium.tls: "true"
      traefik.http.routers.trilium.rule: "Host(`notes.{{project_tld}}`)"
      traefik.http.routers.trilium.service: "trilium"
      traefik.http.services.trilium.loadbalancer.server.port: "8080"
      traefik.enable: "true"
  tags: trilium
